ALIASES = {
    "beer": ("cerveza", "cervezas", "beer"), "coffee": ("cafe", "coffee", "espresso", "latte", "americano", "frappuccino"), "tea": ("te", "tea"),
    "infusions": ("infusion",), "cocktails": ("cocktail", "mojito", "gin tonic"),
    "soft drinks": ("refresco", "coca cola", "cocacola", "fanta", "sprite", "pepsi"),
    "juice": ("zumo", "juice"), "smoothie": ("smoothie", "batido"),
    "tintos": ("vino tinto", "tinto"), "blancos": ("vino blanco", "blanco"), "rosados": ("vino rosado", "rosado"),
    "pizza": ("pizza", "pizzas"), "calzone": ("calzone", "calzones"), "sushi": ("sushi",),
    "burger": ("hamburguesa", "burger"), "sandwich": ("sandwich", "bocadillo"),
    "taco": ("taco",), "kebab": ("kebab", "durum"), "hot dog": ("hot dog", "perrito"),
    "empanada": ("empanada",), "burrito": ("burrito",), "arepa": ("arepa",),
    "fries": ("patatas fritas", "fries"), "croquetas": ("croqueta", "croquetas"),
    "pasta varieties": ("pasta", "spaghetti", "espagueti", "espaguetis", "macarron", "macarrones", "macarrons"), "noodles": ("noodle", "fideo", "fideos", "tallarines", "udon", "ramen"),
    "lasagna": ("lasaña", "lasagna"), "canelones": ("canelon", "cannelloni"),
    "paella": ("paella",), "risotto": ("risotto",), "mediterranean rice": ("arroz",),
    "salads": ("ensalada", "amanida", "salad"), "poke": ("poke",), "sauces": ("salsa", "sauce"),
    "bread": ("pan", "bread", "naan"), "tapas": ("tapa", "tapas"), "pinchos": ("pincho",), "nachos": ("nacho",),
    "toasts": ("tosta", "toast"), "chicken": ("pollo", "chicken"), "beef": ("ternera", "vacuno", "beef"),
    "pork": ("cerdo", "pork"), "lamb": ("cordero", "lamb"), "duck": ("pato", "duck"),
    "salmon": ("salmon",), "tuna": ("atun", "tuna"), "cod": ("bacalao", "cod"),
    "squid": ("calamar", "squid"), "octopus": ("pulpo", "octopus"),
    "prawn": ("gamba", "gambas", "langostino", "langostinos", "prawn"), "mussels": ("mejillon", "mussels", "mussel"),
    "ice cream": ("helado", "ice cream"), "cakes": ("tarta", "cake"), "crepes": ("crepe",),
    "waffles": ("gofre", "waffle"), "pancakes": ("pancake",),
    "pastries": ("pastel", "bolleria", "croissant"), "chocolate": ("chocolate",), "cheese": ("queso", "cheese"),
}
